### PR TITLE
importexport: Fix readOnly pad export

### LINKED ISSUE #3154: No export possible when using read-only ID
I'm embedding Etherpads with the read-only ID. When I display the import/export button it does not show the import/upload dialog (as expected) but it show the export links. If I click on a link I get a "403 - Can't touch this" from the Etherpad server. I think it still should be possible to export and Etherpad when using read-only as this is also just a read operation.

### PR DESCRIPTION
**Pull request by pedrobmarin**
The export request hook wasn't testing if the pad's id was from a read-only
pad before validating with the pad manager.

This includes an extra step that makes the read-only id verification and also
avoids setting the original pad's id as the file's name.

Closes #3154.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Any chance you can include some test coverage please?

**Comment by pedrobmarin** [comment]
Sure. Is there any example I could follow up?

**Comment by JohnMcLear** [comment]
Maybe the export URL frontend tests?

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/blob/develop/tests/frontend/specs/importexport.js

@pedrobmarin

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/blob/develop/tests/frontend/specs/embed_value.js @pedrobmarin this is specific for embed URI...  Checks correct URL Etc.

**Comment by pedrobmarin** [comment]
Sorry @JohnMcLear . Totally forgot about this.

I'll send a PR ASAP

File: src/node/handler/ExportHandler.js [hunk 1]
```diff
@@ -49,9 +49,10 @@ const tempDirectory = os.tmpdir();
 /**
  * do a requested export
  */
-async function doExport(req, res, padId, type)
+async function doExport(req, res, padId, readOnlyId, type)
```
Comment (JohnMcLear) [inline src/node/handler/ExportHandler.js:52]: we need to make sure doExport is not called anywhere else.

**Comment by JohnMcLear** [comment]
This PR looks good but we need test coverage
