### PR TITLE
Don't throw error and allow attributes to be cleared on first line if line has line attribute

### LINKED ISSUE #5128: RangeError when clearing authorship when line 1 has line attributes
**Describe the bug**

Clicking the "clear authorship" button throws a RangeError if the first line in the pad has line attributes:

```
RangeError: selection starts before line start -- {
  errorId: '5DKIM2Ru2LXCJJhLRegR',
  type: 'Uncaught exception',
  msg: 'RangeError: selection starts before line start',
  url: 'http://localhost:9001/p/testing',
  source: 'http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function',
  linenumber: 9390,
  userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0',
  stack: '_findRowRange@http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function:9390:43\n' +
    'setAttributesOnRange@http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function:9362:39\n' +
    'performDocumentApplyAttributesToCharRange@http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function:1599:30\n' +
    'registerDefaultCommands/<@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:2436:15\n' +
    'registerAceCommand/</<@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:2161:19\n' +
    'wrapper@http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function:646:27\n' +
    'wrapper@http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function:652:9\n' +
    'inCallStack@http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function:365:16\n' +
    'Ace2Inner/editorInfo.ace_callWithAce@http://localhost:9001/static/js/require-kernel.js?v=a88ec0d9 line 226 > Function:657:25\n' +
    'Ace2Editor/this[fnName]<@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:3069:29\n' +
    'action@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:3030:31\n' +
    'pendingInit/<@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:3031:24\n' +
    'registerAceCommand/<@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:2160:13\n' +
    'triggerCommand@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:2167:27\n' +
    'init/</<@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:2103:16\n' +
    'ep_etherpad-lite/static/js/pad_editbar.js/ToolbarItem.prototype.bind/<@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=a88ec0d9:2035:15\n' +
    'dispatch@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=a88ec0d9:5478:27\n' +
    'add/elemData.handle@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=a88ec0d9:5286:28\n'
}
```

**To Reproduce**
1. Create a new pad
2. Make the first line a bulleted list
3. Click "clear authorship"

**Server (please complete the following information):**
 - Etherpad version: Current tip of `develop` (commit ed6fa9400a1283c6d33d4fd7983caa383d0e084a)
 - OS: Ubuntu 20.04
 - Node.js version (`node --version`): v14.17.2
 - npm version (`npm --version`): 6.14.13

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 90

### PR DESCRIPTION
**Pull request by JohnMcLear**
Fixes #5128

Includes tests.

### CODE REVIEW

File: src/tests/frontend/specs/clear_authorship_colors.js [hunk 1]
```diff
@@ -98,4 +99,46 @@ describe('clear authorship colors button', function () {
...
+
+    // Set some new text
+    const sentText = 'Hello';
+
+    const textElement = inner$('div');
+    inner$('div').parent().children('div').remove();
+
+    // wait until everything is removed then send the string
+    await helper.waitForPromise(() => inner$('div').length === 1);
+    inner$('div').first().sendkeys(sentText);
```
Comment (rhansen) [inline src/tests/frontend/specs/clear_authorship_colors.js:119]: This can be simplified:

```suggestion
    await helper.clearPad();
    await helper.edit('Hello');
```

File: src/tests/frontend/specs/clear_authorship_colors.js [hunk 2]
```diff
@@ -98,4 +99,46 @@ describe('clear authorship colors button', function () {
...
+    // make it a list
+    const $insertunorderedlistButton = chrome$('.buttonicon-insertunorderedlist');
+    $insertunorderedlistButton.click();
+
+    // wait until we have the full value available
+    await helper.waitForPromise(
+        () => inner$('div span').first().attr('class').indexOf('author') !== -1);
+
+    // IE hates you if you don't give focus to the inner frame bevore you do a clearAuthorship
+    inner$('div').first().focus();
```
Comment (rhansen) [inline src/tests/frontend/specs/clear_authorship_colors.js:130]: We don't support IE anymore.

```suggestion
```

File: src/tests/frontend/specs/clear_authorship_colors.js [hunk 3]
```diff
@@ -98,4 +99,46 @@ describe('clear authorship colors button', function () {
...
+    const textElement = inner$('div');
+    inner$('div').parent().children('div').remove();
+
+    // wait until everything is removed then send the string
+    await helper.waitForPromise(() => inner$('div').length === 1);
+    inner$('div').first().sendkeys(sentText);
+
+    // make it a list
+    const $insertunorderedlistButton = chrome$('.buttonicon-insertunorderedlist');
+    $insertunorderedlistButton.click();
```
Comment (rhansen) [inline src/tests/frontend/specs/clear_authorship_colors.js:123]: No need for a comment, or for a separate variable:

```suggestion
    chrome$('.buttonicon-insertunorderedlist').click();
```

File: src/tests/frontend/specs/clear_authorship_colors.js [hunk 4]
```diff
@@ -98,4 +99,46 @@ describe('clear authorship colors button', function () {
...
+    // wait until we have the full value available
+    await helper.waitForPromise(
+        () => inner$('div span').first().attr('class').indexOf('author') !== -1);
+
+    // IE hates you if you don't give focus to the inner frame bevore you do a clearAuthorship
+    inner$('div').first().focus();
+
+    // get the clear authorship colors button and click it
+    const $clearauthorshipcolorsButton = chrome$('.buttonicon-clearauthorship');
+    $clearauthorshipcolorsButton.click();
```
Comment (rhansen) [inline src/tests/frontend/specs/clear_authorship_colors.js:134]:
```suggestion
    chrome$('.buttonicon-clearauthorship').click();
```

File: src/tests/frontend/specs/clear_authorship_colors.js [hunk 5]
```diff
@@ -98,4 +99,46 @@ describe('clear authorship colors button', function () {
...
+    await helper.waitForPromise(() => inner$('div').length === 1);
+    inner$('div').first().sendkeys(sentText);
+
+    // make it a list
+    const $insertunorderedlistButton = chrome$('.buttonicon-insertunorderedlist');
+    $insertunorderedlistButton.click();
+
+    // wait until we have the full value available
+    await helper.waitForPromise(
+        () => inner$('div span').first().attr('class').indexOf('author') !== -1);
```
Comment (rhansen) [inline src/tests/frontend/specs/clear_authorship_colors.js:127]:
```suggestion
    await helper.waitForPromise(() => inner$('[class*="author"]').length > 0);
```

File: src/tests/frontend/specs/clear_authorship_colors.js [hunk 6]
```diff
@@ -98,4 +99,46 @@ describe('clear authorship colors button', function () {
...
+    // IE hates you if you don't give focus to the inner frame bevore you do a clearAuthorship
+    inner$('div').first().focus();
+
+    // get the clear authorship colors button and click it
+    const $clearauthorshipcolorsButton = chrome$('.buttonicon-clearauthorship');
+    $clearauthorshipcolorsButton.click();
+
+    // does the first div include an author class?
+    let hasAuthorClass = inner$('div').first().attr('class').indexOf('author') !== -1;
+    expect(hasAuthorClass).to.be(false);
```
Comment (rhansen) [inline src/tests/frontend/specs/clear_authorship_colors.js:138]:
```suggestion
    await helper.waitForPromise(() => inner$('[class*="author"]').length === 0);
```

File: src/tests/frontend/specs/clear_authorship_colors.js [hunk 7]
```diff
@@ -98,4 +99,46 @@ describe('clear authorship colors button', function () {
...
+
+    await helper.waitForPromise(
+        () => chrome$('div.disconnected').attr('class').indexOf('visible') === -1);
+  });
+
```
Comment (rhansen) [inline src/tests/frontend/specs/clear_authorship_colors.js:143]: This might be true even if there is a problem. It would be better to reload the pad and look for authorship.

File: src/static/js/AttributeManager.js [hunk 8]
```diff
@@ -102,9 +102,11 @@ AttributeManager.prototype = _(AttributeManager.prototype).extend({
         this.rep.lines.offsetOfIndex(row + 1) - this.rep.lines.offsetOfIndex(row) - 1;
     const markerWidth = this.lineHasMarker(row) ? 1 : 0;
     if (lineLength - markerWidth < 0) throw new Error(`line ${row} has negative length`);
-
     const startCol = row === start[0] ? start[1] : markerWidth;
-    if (startCol - markerWidth < 0) throw new RangeError('selection starts before line start');
+
+    if ((startCol !== 0) && (startCol - markerWidth < 0)) {
+      throw new RangeError('selection starts before line start');
+    }
```
[the remark this answers is not in the document]
Comment (JohnMcLear) [reply src/static/js/AttributeManager.js:109]: It absolutely is, its a hammer to fix a vase.

File: src/tests/frontend/specs/clear_authorship_colors.js (hunk 7 above)
Comment (JohnMcLear) [reply src/tests/frontend/specs/clear_authorship_colors.js:123]: Doesn't the logic already check for authorship?  If a changeset was rejected then the user would be disconnected no?  What am I missing here?

Comment (rhansen) [reply src/tests/frontend/specs/clear_authorship_colors.js:123]: There's a race condition. The disconnected div might not be immediately visible, so the `=== -1` check would return true the first time `waitForPromise()` runs the check, which would cause the test to pass even though the user will be disconnected.

If you instead reload the pad then look for authorship you're guaranteed to know that the clear authorship instruction propagated to the server and was accepted.

File: src/static/js/AttributeManager.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (rhansen) [reply src/static/js/AttributeManager.js:109]: I think it would be better to adjust the column past the line marker so that the behavior is consistent across lines:

```javascript
    if (start[1] < 0) throw new RangeError('selection starts at negative column');
    const startCol = Math.max(markerWidth, row === start[0] ? start[1] : 0);
    if (startCol > lineLength) throw new RangeError('selection starts after line end');

    if (end[1] < 0) throw new RangeError('selection ends at negative column');
    const endCol = Math.max(markerWidth, row === end[0] ? end[1] : lineLength);
    if (endCol > lineLength) throw new RangeError('selection ends after line end');
    if (startCol > endCol) throw new RangeError('selection ends before it starts');
```

**Comment by rhansen** [comment]
I rebased onto latest develop and made some changes to address my comments. I also fixed the `rep.selStart` and `rep.selEnd` documentation.
