### PR TITLE
ace.js: Don't use srcdoc when creating iframes

### LINKED ISSUE #4975: 1.8.13: page load broken with `'self'` content security policy (Ace2Editor.init() error event while waiting for load event)
**Describe the bug**
After updating from 1.8.12 to 1.8.13 (no plugins, plain packaged version that I provide in the AUR), I get the following on loading any pad:

```
An error occurred

Please press and hold Ctrl and press F5 to reload this page

If the problem persists, please send this error message to your webmaster:
ErrorId: Hlk02KxskYcOry455748
Unhandled Promise rejection
URL: https://my-pad.tld/p/test
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
Ace2Editor.init() error event while waiting for load event
at https://my-pad.tld/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=580f7db7 at line 49
```

Reloading the page doe not fix the issue.

**To Reproduce**
1. Go to any pad
2. See error

**Expected behavior**
pad loads normally

**Screenshots**
screenshot-2021-03-25_20-28-38_blur

**Server (please complete the following information):**
 - Etherpad version: 1.8.13
 - OS: Arch Linux
 - Node.js version (`node --version`): v15.12.0
 - npm version (`npm --version`): 7.7.4

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 87.0

**Smartphone (please complete the following information):**

**Additional context**
Downgrading to 1.8.12 fixes the issue.

The PKGBUILD that creates the package can be found here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=etherpad-lite

### PR DESCRIPTION
**Pull request by webzwo0i**
Using srcdoc, especially with multiple nested iframes, seems to be
problematic when using `self` in CSP policies.

Fixes #4975

### CODE REVIEW

File: src/static/js/ace.js [hunk 1]
```diff
@@ -198,7 +198,7 @@ const Ace2Editor = function () {
     //   - Chrome never fires any events on the frame or document. Eventually the document's
     //     readyState becomes 'complete' even though it never fires a readystatechange event.
     //   - Safari behaves like Chrome.
-    outerFrame.srcdoc = '<!DOCTYPE html>';
+    outerFrame.src = '/aceOuter.html';
```
Comment (rhansen) [inline src/static/js/ace.js:201]:
```suggestion
    outerFrame.src = '../aceOuter.html';
```

File: src/static/js/ace.js [hunk 2]
```diff
@@ -241,7 +241,7 @@ const Ace2Editor = function () {
     innerFrame.allowTransparency = true; // for IE
     // The iframe MUST have a src or srcdoc property to avoid browser quirks. See the comment above
     // outerFrame.srcdoc.
-    innerFrame.srcdoc = '<!DOCTYPE html>';
+    innerFrame.src = '/aceInner.html';
```
Comment (rhansen) [inline src/static/js/ace.js:244]:
```suggestion
    innerFrame.src = '../aceInner.html';
```

File: src/static/js/ace2_inner.js [hunk 3]
```diff
@@ -64,7 +64,7 @@ function Ace2Inner(editorInfo, cssManagers) {
   const iframe = window.frameElement;
   const outerWin = iframe.ace_outerWin;
   iframe.ace_outerWin = null; // prevent IE 6 memory leak
-  const sideDiv = iframe.nextSibling;
+  const sideDiv = iframe.parentElement.querySelector('#sidediv');
```
Comment (rhansen) [inline src/static/js/ace2_inner.js:67]: Why is this change needed?

**Review by rhansen — COMMENTED** [review]
I recommend adding a basic HTML skeleton to `aceInner.html` and `aceOuter.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>iframe</title>
  </head>
  <body>
  </body>
</html>
```

File: src/static/js/ace.js (hunk 2 above)
Comment (nuxi) [reply src/static/js/ace.js:244]: I actually needed `innerFrame.src = 'aceInner.html';` for it to work for me,

Comment (rhansen) [reply src/static/js/ace.js:244]: Oops, yup, you're right.

**Comment by rhansen** [comment]
@webzwo0i I pushed some changes to your branch. If everything looks good to you, feel free to merge it.

**Review by rhansen — APPROVED** [review]
