### PR TITLE
bin/safeRun.sh: Fix `try: not found` bug

### LINKED ISSUE #4930: Can’t run Etherpad after upgrade to 1.8.12 : `try: not found`
**Describe the bug**
After upgrading to 1.8.12, I can’t run Etherpad with `safeRun.sh`: it fails saying `try: not found`

**Expected behavior**
`safeRun.sh` should launch Etherpad

**Server (please complete the following information):**
 - Etherpad version: 1.8.12
 - OS: Debian 10
 - Node.js version (`node --version`): v12.21.0
 - npm version (`npm --version`): 6.14.11
 - bash (which launch `safeRun.sh`) version: 5.0.3

**Additional context**
`try` in `safeRun.sh` was introduced in https://github.com/ether/etherpad-lite/commit/8b28e007842efefccf852a55f783761f86dc6090#diff-d9f65dd56d7d1ec3afc44b2c3eadde1d3dcd64513764bcdc0bc1f1cb6512b990

### PR DESCRIPTION
**Pull request by rhansen**
This fixes a copy+paste bug introduced in commit 8b28e007842efefccf852a55f783761f86dc6090 (v1.8.8).

Fixes #4930.

cc @ldidry

### CODE REVIEW

File: src/bin/safeRun.sh [hunk 1]
```diff
@@ -24,8 +24,8 @@ fatal() { error "$@"; exit 1; }
 LAST_EMAIL_SEND=0
 
 # Move to the Etherpad base directory.
-MY_DIR=$(try cd "${0%/*}" && try pwd -P) || exit 1
-try cd "${MY_DIR}/../.."
+MY_DIR=$(cd "${0%/*}" && pwd -P) || exit 1
+cd "${MY_DIR}/../.." || exit 1
```
Comment (ldidry) [inline src/bin/safeRun.sh:28]:
```suggestion
cd "${MY_DIR}/../.." || fatal "Couldn't go to ${MY_DIR}/../.."
```

**Review by ldidry — COMMENTED** [review]
No problem :-)

File: src/bin/safeRun.sh (hunk 1 above)
Comment (ldidry) [reply src/bin/safeRun.sh:28]: No problem :slightly_smiling_face:

**Comment by rhansen** [comment]
Thanks for the bug report and the review @ldidry!
